### ISSUE TITLE
Use ArrayAccessorTrait

### ISSUE THREAD

**Issue by shadowhand** [michaelKaefer/oauth2-wrike#1]
The [`ArrayAccessor`](https://github.com/thephpleague/oauth2-client/blob/2.0.0/src/Tool/ArrayAccessorTrait.php) can be used instead of [manual key checks](https://github.com/michaelKaefer/oauth2-wrike/blob/master/src/Provider/WrikeResourceOwner.php#L33). Example [here](https://github.com/thephpleague/oauth2-github/blob/master/src/Provider/GithubResourceOwner.php#L40).

**Comment by michaelKaefer** [comment]
Fixed it! Thx!
